1. You are given two strings s and t. String t is generated by randomly
shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.
Examples
find_the_difference("abcd", "abcde") ➞ "e"
find_the_difference("", "y") ➞ "y"
find_the_difference("ae", "aea") ➞ "a"

In [16]:
def find_the_difference(x,y):
    dif=[]
    for i in y:
        if i in x:
            y = y.replace(i, '', 1)
            x = x.replace(i, '', 1)
            
    return y

In [17]:
find_the_difference("abcd", "abcde")

'e'

In [18]:
find_the_difference("", "y")

'y'

In [19]:
find_the_difference("ae", "aea")

'a'

2. Given a function that accepts unlimited arguments, check and count how
many data types are in those arguments. Finally return the total in a list.
List order is:
[int, str, bool, list, tuple, dictionary]
Examples
count_datatypes(1, 45, "Hi", False) ➞ [2, 1, 1, 0, 0, 0]
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1,
3], {"Brayan": 18}, 25, 23) ➞ [2, 2, 3, 1, 0, 2]
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]) ➞ [2,
0, 1, 2, 2, 0]

In [34]:
def count_datatypes(*args):
    dt={int:0, str:1, bool:2, list:3, tuple:4, dict:5}
    lst=[0,0,0,0,0,0]
    
    for i in args:
        typ=type(i)
        index=dt[typ]
        lst[index]+=1
    return lst

In [35]:
count_datatypes(1, 45, "Hi", False)

[2, 1, 1, 0, 0, 0]

In [36]:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

In [31]:
if type(1)==int:
    print('o')

o

In [37]:
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1,
3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [38]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

3. A Fibonacci string is a precedence of the Fibonacci series. It works with
any two characters of the English alphabet (as opposed to the numbers 0 and
1 in the Fibonacci series) as the initial items and concatenates them together
as it progresses in a similar fashion as the Fibonacci series.
Examples
fib_str(3, ["j", "h"]) ➞ "j, h, hj"
fib_str(5, ["e", "a"]) ➞ "e, a, ae, aea, aeaae"
fib_str(6, ["n", "k"]) ➞ "n, k, kn, knk, knkkn, knkknknk"

In [72]:
def fib_str(n,strng):
    if n<=len(strng):
        return "enter number more than {} (number of strings)".format(len(strng))
    for i in range(n-2):
        a=''
        a=''.join((strng[-1],strng[-2]))
        strng.append(a)
    return strng

In [73]:
fib_str(3, ["j", "h"])

['j', 'h', 'hj']

In [75]:
fib_str(5, ["e", "a"])

['e', 'a', 'ae', 'aea', 'aeaae']

In [76]:
fib_str(6, ["n", "k"])

['n', 'k', 'kn', 'knk', 'knkkn', 'knkknknk']

4. Given an integer between 0 and 26, make a variable (self.answer). That
variable would be assigned to a string in this format:
"nines:your answer, threes:your answer, ones:your answer"
You need to find out how many ones, threes, and nines it would at least take
for the number of each to add up to the given integer when multiplied by one,
three or nine (depends).
Examples
ones_threes_nines(10) ➞ "nines:1, threes:0, ones:1"
ones_threes_nines(15) ➞ "nines:1, threes:2, ones:0"
ones_threes_nines(22) ➞ "nines:2, threes:1, ones:1"

In [98]:
def ones_threes_nines(num):
    nines=0
    threes=0
    ones=0
    if 0<num<=26:
        rem9=num%9
        nines=num//9
        rem3=rem9%3
        threes=rem9//3
        ones=rem3//1
        return "nines:{}, threes:{}, ones:{}".format(nines,threes,ones)
    
    else:
        return "enter numbers between 0 to 26"

In [99]:
ones_threes_nines(10)

'nines:1, threes:0, ones:1'

In [100]:
ones_threes_nines(15)

'nines:1, threes:2, ones:0'

In [101]:
ones_threes_nines(22)

'nines:2, threes:1, ones:1'

In [102]:
ones_threes_nines(-1)

'enter numbers between 0 to 26'

5. The Fibonacci sequence is a classic use case for recursive functions since
the value of the sequence at a given index is dependent on the sum of the
last two values. However, the recursion tree created by solving the Fibonacci
sequence recursively can grow quite fast. Therefore it can be important to
think about the implications of running a function recursively. Depending on
the size of n needed and the capabilities of the system in question you might
want to take a different approach.
Write a non-recursive function that takes an integer n and returns the
Fibonacci sequence's value at index n.
Examples
fib(6) ➞ 8
# 0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8
fib(1) ➞ 1
fib(2) ➞ 1

In [108]:
def fib(num):
    count = 0
    f1 , f2 = 0,1
    if num <= 0:
        print("Number not greater than 0")
    elif num == 1:
        return num       
    else:
        while count <= num:   
            count+=1
            if count > num:
                return f1
            fth = f1 + f2
            f1,f2 = f2, fth

In [109]:
fib(6)

8

In [110]:
fib(1)

1

In [111]:
fib(2)

1

In [112]:
fib(0)

Number not greater than 0